License Command update
Underground-Roleplay/framework pull request #49
Opened 2022-01-07 02:43 UTC by battlezoneyt

1.License add remove command update
2. Formated to the core.
3. Fixed typo error in notification.

2022-01-08 18:06 UTC, xipanca requested changes
need to remove the else if use only if returning the error message

2022-01-08 18:07 UTC, xipanca approved these changes

2022-01-08 18:07 UTC, xipanca approved these changes

2022-01-08 18:08 UTC, xipanca approved these changes

2022-01-08 18:09 UTC, xipanca approved these changes

2022-01-08 20:49 UTC, Galatimus commented
good

2022-01-09 02:16 UTC, xipanca approved these changes

2022-01-09 02:16 UTC, merged